# mysql -u root --password=root --host=127.0.0.1 --port=...
version: '3.7'
services:
  database:
    image: 'mysql:8.0'
    environment:
      MYSQL_DATABASE: snowtricks
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306'